# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DevNotes
email: svitlana.dzyuban@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Svitlana Dzyuban (LanaDz) - Software Engineer.
  Dev Journal's goal is to keep and share thoughts, ideas, helpful info and just have fun.
  I really hope you find something interesting here.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://lanadz.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SvitlanaDz
github_username: lanadz
linkedin_username: lanadz

# Build settings
markdown: kramdown
#theme: minima
sass:
  sass_dir: /_scss

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 9

excerpt_separator: <!--more-->
permalink: /tags/:title/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
